In [1]:
import pandas as pd
import glob
import numpy as np

In [2]:
scores_retrotesting = pd.read_hdf("scores_retrotesting.hd5")

In [3]:
scores_retrotesting=scores_retrotesting[scores_retrotesting['10_True_0.05'] == 1.0]

In [4]:
scores_retrotesting

,observation_id,news_id,10_True_0.05,ticker,final_score,final_probabilities,probability_of_conversion_calibrated_by_source.name,probability
45,1692,0bbb3403279779b81fe6bc1fe556ff69,1.0,CTSO,0.676775,0.663018,0.117365,0.092352
117,3955,1b754b1268deb3b6b6ed6a83ee7104ac,1.0,HALL,2.327082,0.911095,0.188943,0.164786
134,4460,1ef7ccd09c652ee1bcc653eb9a9d857c,1.0,CAPR,-0.279799,0.430503,0.085970,0.064822
191,6143,2b3788b24dc64e622ec4b47b19de2521,1.0,SLGG,-0.450264,0.389298,0.081423,0.060797
236,7259,33b7d9486f20c0a6c296c8860c6bf00f,1.0,ABNB,0.317014,0.578596,0.105342,0.080942
...,...,...,...,...,...,...,...,...
35775,34503,f27639fb94b4d032620d815e47d610d2,1.0,LW,-0.014444,0.496389,0.079369,0.071584
36039,12703,595e96d8289fd6df85dd64716680872f,1.0,BCYC,-2.939528,0.050234,0.037688,0.023286
36176,21378,95a136d40f47c8db3c0a851991f38fc7,1.0,REDU,-0.658707,0.341030,0.078057,0.056193
36287,30296,d573a87ede50634009cbb32ba331dca9,1.0,AGRX,-0.501690,0.377144,0.080094,0.059629
36314,31425,dd495e51b0949e9e8047f1ccb881e536,1.0,BHAT,0.915918,0.714210,0.126001,0.100716

In [5]:
ticker_price = pd.read_hdf("ticker_price_moment_exit.hd5")

In [6]:
DF = scores_retrotesting.merge(ticker_price, how ='left', on = ['news_id', 'ticker'])

In [7]:
DF1=DF[['news_id', 'ticker','timestamp', 'current_price']]

In [11]:
all_files = glob.glob("2021-08-13*.hd5")

In [12]:
all_files

['2021-08-13.hd5']

In [13]:
liis = []
for filename in all_files:
    df = pd.read_hdf(filename, index_col=None, header=0)
    liis.append(df)
intraday = pd.concat(liis, axis=0, ignore_index=True)

In [14]:
intraday

,open,high,close,low,volume,time,formated time,ticker,autofilled
0,45.690,45.690,45.690,45.690,100.0,1628861340,2021-08-13 13:29:00+00:00,WERN,False
1,45.730,45.830,45.800,45.730,5078.0,1628861400,2021-08-13 13:30:00+00:00,WERN,False
2,45.770,45.770,45.770,45.770,359.0,1628861460,2021-08-13 13:31:00+00:00,WERN,False
3,45.720,45.720,45.650,45.650,1700.0,1628861520,2021-08-13 13:32:00+00:00,WERN,False
4,45.580,45.630,45.600,45.580,1191.0,1628861580,2021-08-13 13:33:00+00:00,WERN,False
...,...,...,...,...,...,...,...,...,...
431822,53.980,54.110,54.100,53.900,15488.0,1628884560,2021-08-13 19:56:00+00:00,EYE,False
431823,54.040,54.090,54.075,53.970,17361.0,1628884620,2021-08-13 19:57:00+00:00,EYE,False
431824,54.060,54.100,54.075,54.015,29836.0,1628884680,2021-08-13 19:58:00+00:00,EYE,False
431825,54.075,54.075,53.960,53.960,6389.0,1628884740,2021-08-13 19:59:00+00:00,EYE,False
431826,53.980,53.980,53.980,53.980,4653.0,1628884800,2021-08-13 20:00:00+00:00,EYE,False

In [15]:
DAY=intraday[['close', 'time','formated time', 'ticker']]

In [16]:
DF1.dropna()

                              news_id ticker   timestamp current_price
132  11990bf67a5e0941138d285aa0acb5a5    CIO  1629492186          12.9
133  34684b70aee5b3119f8c7ebfa0ff313c    CIO  1629493444          12.9
141  30e66950e1fea601f665a447740a5e88   AXSM  1629713652         21.56
142  377b16b79fd3f3974a0f84bac2efdc2e     EM  1629714607          2.84
143  3824a5cd949c2463c53c54780577f8f3   RNAZ  1629748869         2.815
..                                ...    ...         ...           ...
532  f27639fb94b4d032620d815e47d610d2     LW  1633609807         62.34
533  595e96d8289fd6df85dd64716680872f   BCYC  1633699867         48.74
534  95a136d40f47c8db3c0a851991f38fc7   REDU  1633695307        0.6875
535  d573a87ede50634009cbb32ba331dca9   AGRX  1633696203        0.9423
536  dd495e51b0949e9e8047f1ccb881e536   BHAT  1633698020        0.5899

[383 rows x 4 columns]

In [17]:
CM=DAY[(DAY["ticker"]=="RIBT")]
CM[CM["time"]>1631192488].head(60)#Заходим через минуту выходим через 30

Empty DataFrame
Columns: [close, time, formated time, ticker]
Index: []

In [18]:
CM=DAY[(DAY["ticker"]=="FARM")]
CM[CM["time"]>1631217600].head(30)#Заходим через минуту выходим через 7

Empty DataFrame
Columns: [close, time, formated time, ticker]
Index: []

In [19]:
CM=DAY[(DAY["ticker"]=="CEMI")]
CM[CM["time"]>1630065600].head(30)#Заходим сразу продём через 16

Empty DataFrame
Columns: [close, time, formated time, ticker]
Index: []

In [20]:
CM=DAY[(DAY["ticker"]=="METX")]
CM[CM["time"]>=1630528800].head(30)#Заходим сразу продаём через 18

Empty DataFrame
Columns: [close, time, formated time, ticker]
Index: []

In [107]:
CM=DAY[(DAY["ticker"]=="PBTS")]
CM[CM["time"]>=1630497600].head(30)#Заходим через 2 минуты продаём через 7,8 Снова заходим продаём через 16

          close        time             formated time ticker
7677006  1.5384  1630497600 2021-09-01 12:00:00+00:00   PBTS
7677007  1.5400  1630497660 2021-09-01 12:01:00+00:00   PBTS
7677008  1.5300  1630497720 2021-09-01 12:02:00+00:00   PBTS
7677009  1.4900  1630497780 2021-09-01 12:03:00+00:00   PBTS
7677010  1.5200  1630497840 2021-09-01 12:04:00+00:00   PBTS
7677011  1.5000  1630497900 2021-09-01 12:05:00+00:00   PBTS
7677012  1.5000  1630497960 2021-09-01 12:06:00+00:00   PBTS
7677013  1.5000  1630498020 2021-09-01 12:07:00+00:00   PBTS
7677014  1.5200  1630498080 2021-09-01 12:08:00+00:00   PBTS
7677015  1.5000  1630498140 2021-09-01 12:09:00+00:00   PBTS
7677016  1.7000  1630498200 2021-09-01 12:10:00+00:00   PBTS
7677017  1.7000  1630498260 2021-09-01 12:11:00+00:00   PBTS
7677018  1.6800  1630498320 2021-09-01 12:12:00+00:00   PBTS
7677019  1.6500  1630498380 2021-09-01 12:13:00+00:00   PBTS
7677020  1.6300  1630498440 2021-09-01 12:14:00+00:00   PBTS
7677021  1.5900  1630498500 2021-09-01 12:15:00+00:00   PBTS
7677022  1.5900  1630498560 2021-09-01 12:16:00+00:00   PBTS
7677023  1.6500  1630498620 2021-09-01 12:17:00+00:00   PBTS
7677024  1.6400  1630498680 2021-09-01 12:18:00+00:00   PBTS
7677025  1.6300  1630498740 2021-09-01 12:19:00+00:00   PBTS
7677026  1.6400  1630498800 2021-09-01 12:20:00+00:00   PBTS
7677027  1.6600  1630498860 2021-09-01 12:21:00+00:00   PBTS
7677028  1.6600  1630498920 2021-09-01 12:22:00+00:00   PBTS
7677029  1.6200  1630498980 2021-09-01 12:23:00+00:00   PBTS
7677030  1.6400  1630499040 2021-09-01 12:24:00+00:00   PBTS
7677031  1.6400  1630499100 2021-09-01 12:25:00+00:00   PBTS
7677032  1.6100  1630499160 2021-09-01 12:26:00+00:00   PBTS
7677033  1.6000  1630499220 2021-09-01 12:27:00+00:00   PBTS
7677034  1.6200  1630499280 2021-09-01 12:28:00+00:00   PBTS
7677035  1.6100  1630499340 2021-09-01 12:29:00+00:00   PBTS

In [106]:
CM=DAY[(DAY["ticker"]=="GANX")]
CM[CM["time"]>=1631100500].head(30)#Заходим сразу продаём через 4 Сразу заходим выходим через 21

         close        time             formated time ticker
9089746  10.64  1631100540 2021-09-08 11:29:00+00:00   GANX
9089747  11.97  1631100600 2021-09-08 11:30:00+00:00   GANX
9089748  10.80  1631100660 2021-09-08 11:31:00+00:00   GANX
9089749  11.20  1631100720 2021-09-08 11:32:00+00:00   GANX
9089750  12.25  1631100780 2021-09-08 11:33:00+00:00   GANX
9089751  11.37  1631100840 2021-09-08 11:34:00+00:00   GANX
9089752  10.99  1631100900 2021-09-08 11:35:00+00:00   GANX
9089753  11.05  1631100960 2021-09-08 11:36:00+00:00   GANX
9089754  11.48  1631101020 2021-09-08 11:37:00+00:00   GANX
9089755  11.19  1631101080 2021-09-08 11:38:00+00:00   GANX
9089756  10.80  1631101140 2021-09-08 11:39:00+00:00   GANX
9089757  10.87  1631101200 2021-09-08 11:40:00+00:00   GANX
9089758  10.61  1631101260 2021-09-08 11:41:00+00:00   GANX
9089759  10.63  1631101320 2021-09-08 11:42:00+00:00   GANX
9089760  10.89  1631101380 2021-09-08 11:43:00+00:00   GANX
9089761  10.83  1631101440 2021-09-08 11:44:00+00:00   GANX
9089762  10.65  1631101500 2021-09-08 11:45:00+00:00   GANX
9089763  10.75  1631101560 2021-09-08 11:46:00+00:00   GANX
9089764  10.30  1631101620 2021-09-08 11:47:00+00:00   GANX
9089765  10.10  1631101680 2021-09-08 11:48:00+00:00   GANX
9089766  10.20  1631101740 2021-09-08 11:49:00+00:00   GANX
9089767  10.20  1631101800 2021-09-08 11:50:00+00:00   GANX
9089768  10.06  1631101860 2021-09-08 11:51:00+00:00   GANX
9089769  10.00  1631101920 2021-09-08 11:52:00+00:00   GANX
9089770  10.00  1631101980 2021-09-08 11:53:00+00:00   GANX
9089771   9.98  1631102040 2021-09-08 11:54:00+00:00   GANX
9089772  10.05  1631102100 2021-09-08 11:55:00+00:00   GANX
9089773  10.13  1631102160 2021-09-08 11:56:00+00:00   GANX
9089774  10.03  1631102220 2021-09-08 11:57:00+00:00   GANX
9089775  10.06  1631102280 2021-09-08 11:58:00+00:00   GANX

In [111]:
CM=DAY[(DAY["ticker"]=="BASE")]
CM[CM["time"]>=1631131500].head(30)#Заходим сразу выходим через 16 Сразу закупаемся

         close        time             formated time ticker
9214840  52.00  1631131500 2021-09-08 20:05:00+00:00   BASE
9214841  52.00  1631131560 2021-09-08 20:06:00+00:00   BASE
9214842  52.00  1631131620 2021-09-08 20:07:00+00:00   BASE
9214843  52.00  1631131680 2021-09-08 20:08:00+00:00   BASE
9214844  52.00  1631131740 2021-09-08 20:09:00+00:00   BASE
9214845  52.00  1631131800 2021-09-08 20:10:00+00:00   BASE
9214846  49.00  1631131860 2021-09-08 20:11:00+00:00   BASE
9214847  45.99  1631131920 2021-09-08 20:12:00+00:00   BASE
9214848  44.21  1631131980 2021-09-08 20:13:00+00:00   BASE
9214849  44.25  1631132040 2021-09-08 20:14:00+00:00   BASE
9214850  44.40  1631132100 2021-09-08 20:15:00+00:00   BASE
9214851  44.39  1631132160 2021-09-08 20:16:00+00:00   BASE
9214852  44.38  1631132220 2021-09-08 20:17:00+00:00   BASE
9214853  45.50  1631132280 2021-09-08 20:18:00+00:00   BASE
9214854  45.00  1631132340 2021-09-08 20:19:00+00:00   BASE
9214855  44.20  1631132400 2021-09-08 20:20:00+00:00   BASE
9214856  44.10  1631132460 2021-09-08 20:21:00+00:00   BASE
9214857  44.30  1631132520 2021-09-08 20:22:00+00:00   BASE
9214858  44.20  1631132580 2021-09-08 20:23:00+00:00   BASE
9214859  44.50  1631132640 2021-09-08 20:24:00+00:00   BASE
9214860  46.00  1631132700 2021-09-08 20:25:00+00:00   BASE
9214861  46.00  1631132760 2021-09-08 20:26:00+00:00   BASE
9214862  45.02  1631132820 2021-09-08 20:27:00+00:00   BASE
9214863  45.02  1631132880 2021-09-08 20:28:00+00:00   BASE
9214864  45.02  1631132940 2021-09-08 20:29:00+00:00   BASE
9214865  45.02  1631133000 2021-09-08 20:30:00+00:00   BASE
9214866  45.50  1631133060 2021-09-08 20:31:00+00:00   BASE
9214867  45.50  1631133120 2021-09-08 20:32:00+00:00   BASE
9214868  45.50  1631133180 2021-09-08 20:33:00+00:00   BASE
9214869  45.50  1631133240 2021-09-08 20:34:00+00:00   BASE

In [117]:
CM=DAY[(DAY["ticker"]=="AGMH")]
CM[CM["time"]>=1632915900].head(30)#Заходим через минуту выходим через 16

          close        time             formated time ticker
15805714   9.49  1632915900 2021-09-29 11:45:00+00:00   AGMH
15805715   9.71  1632915960 2021-09-29 11:46:00+00:00   AGMH
15805716   9.45  1632916020 2021-09-29 11:47:00+00:00   AGMH
15805717   9.16  1632916080 2021-09-29 11:48:00+00:00   AGMH
15805718   9.20  1632916140 2021-09-29 11:49:00+00:00   AGMH
15805719   9.32  1632916200 2021-09-29 11:50:00+00:00   AGMH
15805720   9.12  1632916260 2021-09-29 11:51:00+00:00   AGMH
15805721   9.12  1632916320 2021-09-29 11:52:00+00:00   AGMH
15805722   9.12  1632916380 2021-09-29 11:53:00+00:00   AGMH
15805723   9.01  1632916440 2021-09-29 11:54:00+00:00   AGMH
15805724   9.01  1632916500 2021-09-29 11:55:00+00:00   AGMH
15805725   9.01  1632916560 2021-09-29 11:56:00+00:00   AGMH
15805726   8.81  1632916620 2021-09-29 11:57:00+00:00   AGMH
15805727   8.81  1632916680 2021-09-29 11:58:00+00:00   AGMH
15805728   8.88  1632916740 2021-09-29 11:59:00+00:00   AGMH
15805729   9.45  1632916800 2021-09-29 12:00:00+00:00   AGMH
15805730   9.45  1632916860 2021-09-29 12:01:00+00:00   AGMH
15805731   8.85  1632916920 2021-09-29 12:02:00+00:00   AGMH
15805732   9.90  1632916980 2021-09-29 12:03:00+00:00   AGMH
15805733   9.00  1632917040 2021-09-29 12:04:00+00:00   AGMH
15805734   9.00  1632917100 2021-09-29 12:05:00+00:00   AGMH
15805735   9.00  1632917160 2021-09-29 12:06:00+00:00   AGMH
15805736   9.00  1632917220 2021-09-29 12:07:00+00:00   AGMH
15805737   9.00  1632917280 2021-09-29 12:08:00+00:00   AGMH
15805738   9.00  1632917340 2021-09-29 12:09:00+00:00   AGMH
15805739   9.00  1632917400 2021-09-29 12:10:00+00:00   AGMH
15805740   9.00  1632917460 2021-09-29 12:11:00+00:00   AGMH
15805741   9.00  1632917520 2021-09-29 12:12:00+00:00   AGMH
15805742   9.00  1632917580 2021-09-29 12:13:00+00:00   AGMH
15805743   9.00  1632917640 2021-09-29 12:14:00+00:00   AGMH

In [120]:
CM=DAY[(DAY["ticker"]=="TC")]
CM[CM["time"]>=1632947410].head(30)#Сразу заходим выходим через пару минут, заходим выхоидм через 10

          close        time             formated time ticker
15975466   2.45  1632947460 2021-09-29 20:31:00+00:00     TC
15975467   2.45  1632947520 2021-09-29 20:32:00+00:00     TC
15975468   2.97  1632947580 2021-09-29 20:33:00+00:00     TC
15975469   2.97  1632947640 2021-09-29 20:34:00+00:00     TC
15975470   2.97  1632947700 2021-09-29 20:35:00+00:00     TC
15975471   2.97  1632947760 2021-09-29 20:36:00+00:00     TC
15975472   2.97  1632947820 2021-09-29 20:37:00+00:00     TC
15975473   2.97  1632947880 2021-09-29 20:38:00+00:00     TC
15975474   2.97  1632947940 2021-09-29 20:39:00+00:00     TC
15975475   2.97  1632948000 2021-09-29 20:40:00+00:00     TC
15975476   2.97  1632948060 2021-09-29 20:41:00+00:00     TC
15975477   2.97  1632948120 2021-09-29 20:42:00+00:00     TC
15975478   2.97  1632948180 2021-09-29 20:43:00+00:00     TC
15975479   2.31  1632948240 2021-09-29 20:44:00+00:00     TC
15975480   2.31  1632948300 2021-09-29 20:45:00+00:00     TC
15975481   2.31  1632948360 2021-09-29 20:46:00+00:00     TC
15975482   2.31  1632948420 2021-09-29 20:47:00+00:00     TC
15975483   2.25  1632948480 2021-09-29 20:48:00+00:00     TC
17486556   2.39  1633353240 2021-10-04 13:14:00+00:00     TC
17486557   2.43  1633353300 2021-10-04 13:15:00+00:00     TC
17486558   2.43  1633353360 2021-10-04 13:16:00+00:00     TC
17486559   2.43  1633353420 2021-10-04 13:17:00+00:00     TC
17486560   2.43  1633353480 2021-10-04 13:18:00+00:00     TC
17486561   2.43  1633353540 2021-10-04 13:19:00+00:00     TC
17486562   2.43  1633353600 2021-10-04 13:20:00+00:00     TC
17486563   2.43  1633353660 2021-10-04 13:21:00+00:00     TC
17486564   2.43  1633353720 2021-10-04 13:22:00+00:00     TC
17486565   2.43  1633353780 2021-10-04 13:23:00+00:00     TC
17486566   2.43  1633353840 2021-10-04 13:24:00+00:00     TC
17486567   2.43  1633353900 2021-10-04 13:25:00+00:00     TC

In [125]:
CM=DAY[(DAY["ticker"]=="BLU")]
CM[CM["time"]>=1631533500].head(60)#Сразу заходим , выходим через минуту, можно опять взять и продать через ~40 минут

           close        time             formated time ticker
10842886  4.1400  1631533500 2021-09-13 11:45:00+00:00    BLU
10842887  5.3000  1631533560 2021-09-13 11:46:00+00:00    BLU
10842888  5.1400  1631533620 2021-09-13 11:47:00+00:00    BLU
10842889  4.9100  1631533680 2021-09-13 11:48:00+00:00    BLU
10842890  4.7500  1631533740 2021-09-13 11:49:00+00:00    BLU
10842891  4.8400  1631533800 2021-09-13 11:50:00+00:00    BLU
10842892  4.5000  1631533860 2021-09-13 11:51:00+00:00    BLU
10842893  4.7000  1631533920 2021-09-13 11:52:00+00:00    BLU
10842894  4.7500  1631533980 2021-09-13 11:53:00+00:00    BLU
10842895  4.8800  1631534040 2021-09-13 11:54:00+00:00    BLU
10842896  4.8200  1631534100 2021-09-13 11:55:00+00:00    BLU
10842897  4.8200  1631534160 2021-09-13 11:56:00+00:00    BLU
10842898  4.8200  1631534220 2021-09-13 11:57:00+00:00    BLU
10842899  4.8000  1631534280 2021-09-13 11:58:00+00:00    BLU
10842900  4.8500  1631534340 2021-09-13 11:59:00+00:00    BLU
10842901  4.8500  1631534400 2021-09-13 12:00:00+00:00    BLU
10842902  4.8100  1631534460 2021-09-13 12:01:00+00:00    BLU
10842903  4.8100  1631534520 2021-09-13 12:02:00+00:00    BLU
10842904  4.8200  1631534580 2021-09-13 12:03:00+00:00    BLU
10842905  4.8500  1631534640 2021-09-13 12:04:00+00:00    BLU
10842906  4.8900  1631534700 2021-09-13 12:05:00+00:00    BLU
10842907  4.8900  1631534760 2021-09-13 12:06:00+00:00    BLU
10842908  4.9000  1631534820 2021-09-13 12:07:00+00:00    BLU
10842909  4.8500  1631534880 2021-09-13 12:08:00+00:00    BLU
10842910  4.8800  1631534940 2021-09-13 12:09:00+00:00    BLU
10842911  4.9000  1631535000 2021-09-13 12:10:00+00:00    BLU
10842912  4.9000  1631535060 2021-09-13 12:11:00+00:00    BLU
10842913  4.8900  1631535120 2021-09-13 12:12:00+00:00    BLU
10842914  5.0400  1631535180 2021-09-13 12:13:00+00:00    BLU
10842915  5.2800  1631535240 2021-09-13 12:14:00+00:00    BLU
10842916  5.1900  1631535300 2021-09-13 12:15:00+00:00    BLU
10842917  5.1600  1631535360 2021-09-13 12:16:00+00:00    BLU
10842918  5.1700  1631535420 2021-09-13 12:17:00+00:00    BLU
10842919  5.1101  1631535480 2021-09-13 12:18:00+00:00    BLU
10842920  5.1800  1631535540 2021-09-13 12:19:00+00:00    BLU
10842921  5.1800  1631535600 2021-09-13 12:20:00+00:00    BLU
10842922  5.1800  1631535660 2021-09-13 12:21:00+00:00    BLU
10842923  5.3000  1631535720 2021-09-13 12:22:00+00:00    BLU
10842924  5.2000  1631535780 2021-09-13 12:23:00+00:00    BLU
10842925  5.2300  1631535840 2021-09-13 12:24:00+00:00    BLU
10842926  5.2100  1631535900 2021-09-13 12:25:00+00:00    BLU
10842927  5.2100  1631535960 2021-09-13 12:26:00+00:00    BLU
10842928  5.2000  1631536020 2021-09-13 12:27:00+00:00    BLU
10842929  5.2500  1631536080 2021-09-13 12:28:00+00:00    BLU
10842930  5.2200  1631536140 2021-09-13 12:29:00+00:00    BLU
10842931  5.2100  1631536200 2021-09-13 12:30:00+00:00    BLU
10842932  5.3100  1631536260 2021-09-13 12:31:00+00:00    BLU
10842933  5.2600  1631536320 2021-09-13 12:32:00+00:00    BLU
10842934  5.2400  1631536380 2021-09-13 12:33:00+00:00    BLU
10842935  5.2600  1631536440 2021-09-13 12:34:00+00:00    BLU
10842936  5.3300  1631536500 2021-09-13 12:35:00+00:00    BLU
10842937  5.2500  1631536560 2021-09-13 12:36:00+00:00    BLU
10842938  5.3000  1631536620 2021-09-13 12:37:00+00:00    BLU
10842939  5.3400  1631536680 2021-09-13 12:38:00+00:00    BLU
10842940  5.3300  1631536740 2021-09-13 12:39:00+00:00    BLU
10842941  5.3100  1631536800 2021-09-13 12:40:00+00:00    BLU
10842942  5.2700  1631536860 2021-09-13 12:41:00+00:00    BLU
10842943  5.1700  1631536920 2021-09-13 12:42:00+00:00    BLU
10842944  5.1800  1631536980 2021-09-13 12:43:00+00:00    BLU
10842945  5.0900  1631537040 2021-09-13 12:44:00+00:00    BLU

Шортить ~16 минут рост через минуту заходим ~7 минут